# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: angular
    before: npm install -g @angular/cli@13
    command: |
      cd /workspace/angular-meetup/components/lifecycle
      npm install @angular/material@13.3.9 @angular/cdk@13.3.9
      ng add @angular/material --defaults --skip-confirmation

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
