image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - init: >
      nvm install 14 && 
      nvm use 14 && 
      npm install -g @angular/cli@13 &&
      ng new components --directory=./components/lifecycle --style=scss --routing=true &&
      cd ./components/lifecycle &&
      ng add @angular/material@13
  - command: >
      cd ./components/lifecycle &&
      ng serve --open

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
